### ISSUE TITLE
Code cleanup and refactor

### ISSUE THREAD

**Issue by lachlan-00** [lachlan-00/rb-fileorganizer#9]
@fossfreedom do you have any feature you'd like implemented in the plugin?

I'm going to refactor the code and remove the tagging cause it was hacky and eyed3 still doesnt support python3 properly.

just do movement/db management and do it well.

I'll try and comment it better and make it easier for other people to read it.

**Comment by fossfreedom** [comment]
Hi,

  no specific feature.

I suppose the tagging feature could be reworked using python3-mutagen.  My plugin coverart-search-providers uses this python3 module to provide retagging capabilities.  All modern distros have this in their repositories.

Ubuntu has this python3 module for Wily and later users.  I package this as part of my PPA for earlier ubuntu versions (trusty onwards).

BTW - had a quick look at the stats and rb-fileorganizer has been downloaded 16,397 times since the last release I made (26 Oct 2013) to the PPA.

**Comment by lachlan-00** [comment]
Cool, I'll look at mutagen instead then.

It's good to know it's usable to a lot of people. I really want to focus on making it easier for anyone to pick up and play with.

Thanks for you input, I want yo set some time aside for this soon.
